package com.movie.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Movie")
public class Movie {

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
	@DynamoDBAttribute
	private String title;
	@DynamoDBAttribute
	private String year;

	@DynamoDBAttribute
	private String Budget;

	@DynamoDBAttribute
	private int userReview;
	@DynamoDBAttribute
	private String genre;
	@DynamoDBAttribute
	private String duration;
	@DynamoDBAttribute
	private String country;
	@DynamoDBAttribute
	private String language;


	public Movie(String title, String year,String budget,int userReview, String genre, String duration, String country, String language) {
		this.title=title;
		this.year=year;
		this.Budget=budget;
		this.userReview=userReview;
		this.genre=genre;
		this.duration = duration;
		this.country = country;
		this.language = language;
	}
}