package com.movie.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Movie")
public class Movie {

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
	@DynamoDBAttribute
	private String title;
	@DynamoDBAttribute
	private String yearOfRelease;

	@DynamoDBAttribute
	private String director;

	@DynamoDBAttribute
	private String budget;

	@DynamoDBAttribute
	private String userReview;
	@DynamoDBAttribute
	private String genre;
	@DynamoDBAttribute
	private String duration;
	@DynamoDBAttribute
	private String country;
	@DynamoDBAttribute
	private String lang;


	public Movie(String title, String yearOfRelease,String director, String budget,String userReview, String genre, String duration, String country, String lang) {
		this.title=title;
		this.yearOfRelease=yearOfRelease;
		this.director=director;
		this.budget=budget;
		this.userReview=userReview;
		this.genre=genre;
		this.duration = duration;
		this.country = country;
		this.lang = lang;
	}
}